apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    app: my-app
    env: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      env: blue
  template:
    metadata:
      labels:
        app: my-app
        env: blue
    spec:
      containers:
      - name: my-app-container
        image: bhasmeht/java-app:1.1
        ports:
        - containerPort: 8080
   