apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: my-app
    env: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      env: green
  template:
    metadata:
      labels:
        app: my-app
        env: green
    spec:
      containers:
      - name: my-app-container
        image: bhasmeht/java-app:1.1
        ports:
        - containerPort: 8080
   