apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  selector:
    app: my-app
    env: green
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080  
  type: ClusterIP
  